source_data:
  fig2a_2b: "../source_data/fig_2a_2b_efig1.csv"
  fig2c: "../source_data/fig2c.pickle"
  fig2d: "../source_data/fig2d.pickle"
  fig2e_2f: "../source_data/fig_2e_2f.csv"
  fig3a: "../source_data/fig3a.csv"
  fig3b: "../source_data/fig3b.csv"
  fig3c: "../source_data/fig3c.csv"
  fig3d: "../source_data/fig3d.csv"
  fig4a: "../source_data/fig4a.csv"
  fig4b: "../source_data/fig4b.csv"
  fig4c: "../source_data/fig4c.csv"
  fig5: "../source_data/fig5.csv"
  fig6: "../source_data/fig6.csv"
  efig1: "../source_data/efig1.csv"
  efig2a: "../source_data/efig2a.pkl"
  efig2b: "../source_data/efig2b.pkl"
  efig3a: "../source_data/efig3a.pickle"
  efig3b_amy: "../source_data/efig3b_amy.csv"
  efig3b_tau: "../source_data/efig3b_tau.csv"
  efig4a: "../source_data/efig4a.csv"
  efig4b: "../source_data/efig4b.csv"
  efig4c: "../source_data/efig4c.csv"
  efig4d: "../source_data/efig4d.csv"
  efig4e: "../source_data/efig4e.csv"
  efig4f: "../source_data/efig4f.csv"
  efig6a: "../source_data/efig6a.csv"
  efig6b: "../source_data/efig6b.csv"


output:
  fig2a: "../pdf_plots/fig2a.pdf"
  fig2b: "../pdf_plots/fig2b.pdf"
  fig2c: "../pdf_plots/fig2c.pdf"
  fig2d: "../pdf_plots/fig2d.pdf"
  fig2e: "../pdf_plots/fig2e.pdf"
  fig2f: "../pdf_plots/fig2f.pdf"
  fig3a: "../pdf_plots/fig3a.pdf"
  fig3b: "../pdf_plots/fig3b.pdf"
  fig3c: "../pdf_plots/fig3c.pdf"
  fig3d: "../pdf_plots/fig3d.pdf"
  fig4a: "../pdf_plots/fig4a.pdf"
  fig4b: "../pdf_plots/fig4b.pdf"
  fig4c: "../pdf_plots/fig4c.pdf"
  fig5: "../pdf_plots/fig5.pdf"
  fig6a: "../pdf_plots/fig6a.pdf"
  fig6b: "../pdf_plots/fig6b.pdf"
  fig6c: "../pdf_plots/fig6c.pdf"
  fig6d: "../pdf_plots/fig6d.pdf"
  fig6e: "../pdf_plots/fig6e.pdf"
  efig1a: "../pdf_plots/efig1a.pdf"
  efig1b: "../pdf_plots/efig1b.pdf"
  efig2a: "../pdf_plots/efig2a.pdf"
  efig2b: "../pdf_plots/efig2b.pdf"
  efig3a: "../pdf_plots/efig3a.pdf"
  efig3b: "../pdf_plots/efig3b.pdf"
  efig4a: "../pdf_plots/efig4a.pdf"
  efig4b: "../pdf_plots/efig4b.pdf"
  efig4c: "../pdf_plots/efig4c.pdf"
  efig4d: "../pdf_plots/efig4d.pdf"
  efig4e: "../pdf_plots/efig4e.pdf"
  efig4f: "../pdf_plots/efig4f.pdf"
  efig6a: "../pdf_plots/efig6a.pdf"
  efig6b: "../pdf_plots/efig6b.pdf"
